apiVersion: v1
kind: Secret
metadata:
  name: myslq-secret
  namespace: wordpress
type: Opaque
stringData:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_USER: root
   MYSQL_PASSWORD: toto
   MYSQL_DATABASE: wordpress
